/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */

import controller.Controller;

import javax.swing.JLabel;
import javax.swing.JTable;

import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.ArrayList;

import model.InvoiceHeader;
import model.Invoice_Header_Table_Model;
import model.Invoice_Line_Table_Model;



public class salesInvoiceGeneratorFrame extends javax.swing.JFrame {
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesInvoiceGeneratorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesInvoiceGeneratorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesInvoiceGeneratorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesInvoiceGeneratorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesInvoiceGeneratorFrame().setVisible(true);
                
                //new salesInvoiceGeneratorFrame().setVisible(true);
                salesInvoiceGeneratorFrame frame = new salesInvoiceGeneratorFrame();
                frame.setVisible(true);
                frame.controller.addFile("InvoiceHeader.csv", "InvoiceLines.csv");
            }
        });
    }

    /**
     * Creates new form salesInvoiceGeneratorFrame
     */
    public salesInvoiceGeneratorFrame() {
        initComponents();
    }
    
    public Controller controller = new Controller(this);
    
    private ArrayList<InvoiceHeader> invoices;
    
    public static DateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    private Invoice_Header_Table_Model header_Table_Model;
    
    private Invoice_Line_Table_Model line_Table_Model;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createinvoicebtn = new javax.swing.JButton();
        createinvoicebtn.addActionListener(controller);
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deleteinvoicebtn = new javax.swing.JButton();
        deleteinvoicebtn.addActionListener(controller);
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceItemsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        additembtn = new javax.swing.JButton();
        additembtn.addActionListener(controller);
        invoiceNumberLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerNameLabel6 = new javax.swing.JLabel();
        deleteitembtn = new javax.swing.JButton();
        deleteitembtn.addActionListener(controller);
        InvoiceDateLabel7 = new javax.swing.JLabel();
        InvoiceTotalLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoicetable = new javax.swing.JTable();
        invoicetable.getSelectionModel().addListSelectionListener(controller);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addFileCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        addFileCheckBoxMenuItem4.addActionListener(controller);
        saveDataCheckBoxMenuItem5 = new javax.swing.JCheckBoxMenuItem();
        saveDataCheckBoxMenuItem5.addActionListener(controller);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createinvoicebtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        createinvoicebtn.setText("Create Invoice");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Invoice Number");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Invoice Total");

        deleteinvoicebtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deleteinvoicebtn.setText("Delete Invoice");

        invoiceItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(invoiceItemsTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Customer Name");

        additembtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        additembtn.setText("Add item");

        invoiceNumberLabel5.setText("Invoice Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Invoice Date");

        customerNameLabel6.setText("Customer Name");

        deleteitembtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deleteitembtn.setText("Delete Item");
        deleteitembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteitembtnActionPerformed(evt);
            }
        });

        InvoiceDateLabel7.setText("Invoice Date");

        InvoiceTotalLabel8.setText("Invoice Total");

        invoicetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(invoicetable);

        jMenu1.setText("File");

        addFileCheckBoxMenuItem4.setSelected(true);
        addFileCheckBoxMenuItem4.setText("Add File");
        addFileCheckBoxMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileCheckBoxMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(addFileCheckBoxMenuItem4);

        saveDataCheckBoxMenuItem5.setSelected(true);
        saveDataCheckBoxMenuItem5.setText("Save Data");
        jMenu1.add(saveDataCheckBoxMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(createinvoicebtn)
                        .addGap(35, 35, 35)
                        .addComponent(deleteinvoicebtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(additembtn)
                        .addGap(54, 54, 54)
                        .addComponent(deleteitembtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InvoiceTotalLabel8)
                                    .addComponent(InvoiceDateLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerNameLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(invoiceNumberLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceNumberLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customerNameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(InvoiceDateLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvoiceTotalLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(additembtn)
                        .addComponent(deleteitembtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(createinvoicebtn)
                        .addComponent(deleteinvoicebtn)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFileCheckBoxMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileCheckBoxMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addFileCheckBoxMenuItem4ActionPerformed

    private void deleteitembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteitembtnActionPerformed
        // TODO add your handling code here:
           
    }//GEN-LAST:event_deleteitembtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

 
    public InvoiceHeader getInvoiceByNumber(int num) {
        for (InvoiceHeader inv : getInvoices()) {
            if (num == inv.getNumber()) {
                return inv;
            }
        }
        return null;
    }
    
    public int getNextInvoiceNumber() {
        int number = 0;
        for (InvoiceHeader inv : getInvoices()) {
            if (number < inv.getNumber()) {
                number = inv.getNumber();
            }
        }
        
        return ++number;
    }
    
    public ArrayList<InvoiceHeader> getInvoices() {
        if (invoices == null) 
            invoices = new ArrayList<>();
        return invoices;
    }

    public JLabel getInvoiceDateLabel7() {
        return InvoiceDateLabel7;
    }

    public JLabel getInvoiceTotalLabel8() {
        return InvoiceTotalLabel8;
    }

    public JLabel getCustomerNameLabel6() {
        return customerNameLabel6;
    }

    public JLabel getInvoiceNumberLabel5() {
        return invoiceNumberLabel5;
    }

    public Controller getController() {
        return controller;
    }

    public Invoice_Header_Table_Model getHeader_Table_Model() {
        return header_Table_Model;
    }

    public void setHeader_Table_Model(Invoice_Header_Table_Model header_Table_Model) {
        this.header_Table_Model = header_Table_Model;
    }
    
    public Invoice_Line_Table_Model getLine_Table_Model() {
        return line_Table_Model;
    }

    public void setLine_Table_Model(Invoice_Line_Table_Model line_Table_Model) {
        this.line_Table_Model = line_Table_Model;
    }

    public JTable getInvoiceItemsTable() {
        return invoiceItemsTable;
    }
    
     public void setInvoiceItemsTable(Invoice_Line_Table_Model line_Table_Model) {
        
    }

    public JTable getInvoicetable() {
        return invoicetable;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InvoiceDateLabel7;
    private javax.swing.JLabel InvoiceTotalLabel8;
    private javax.swing.JCheckBoxMenuItem addFileCheckBoxMenuItem4;
    private javax.swing.JButton additembtn;
    private javax.swing.JButton createinvoicebtn;
    private javax.swing.JLabel customerNameLabel6;
    private javax.swing.JButton deleteinvoicebtn;
    private javax.swing.JButton deleteitembtn;
    private javax.swing.JTable invoiceItemsTable;
    private javax.swing.JLabel invoiceNumberLabel5;
    private javax.swing.JTable invoicetable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBoxMenuItem saveDataCheckBoxMenuItem5;
    // End of variables declaration//GEN-END:variables

    

   

   

    
    

    
}
